---
- name: Provision server and install Nginx
  hosts: web
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Create HTML directory
      file:
        path: /var/www/html
        state: directory
        mode: 0755

    - name: Create index.html
      copy:
        content: "<html><body><h1>Welcome to my Nginx server! My name is Shubham.</h1></body></html>"
        dest: /var/www/html/index.html

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
